### ISSUE TITLE
Unable to submit hash via cli

### ISSUE THREAD

**Issue by cogweh** [chainpoint/chainpoint-core#35]
Using the instructions here:
https://github.com/chainpoint/chainpoint-cli

```
npm i -g chainpoint-cli

chp submit 6efd383745a964768989b9df420811abc6e5873f874fc22a76fe9258e020c2e1
Cannot set property 'submitted_to' of undefined
Cannot set property 'submitted_to' of undefined
Cannot set property 'submitted_to' of undefined
Cannot set property 'submitted_to' of undefined
Cannot set property 'submitted_to' of undefined
Cannot set property 'submitted_to' of undefined
6efd383745a964768989b9df420811abc6e5873f874fc22a76fe9258e020c2e1 | Unable to submit at this time, try again
```

**Comment by jacohend** [comment]
Hi @cogweh , you'll need an actual gateway uri to pass to the cli via the flag `--gateway_uri`. You can use one of 

- http://3.17.155.208 
- http://18.191.50.129
- http://18.224.185.143

**Comment by cogweh** [comment]
Hi @jacohend, I can submit to the second ip this time around. Seems proof generation is slow going? I did previously try both the main and testnet gateway IPs listed on twitter. Have not been able to make a full round of calls complete (submission -> validation).

**Comment by jacohend** [comment]
@cogweh You should be able to retrieve a Calendar (our blockchain) proof within 3 minutes. A bitcoin proof (where our blockchain anchors to btc) requires 90 minutes to confirm. 

The first IP is under maintenance right now. We'll look into why you weren't able to submit to the testnet.

**Comment by cogweh** [comment]
@jacohend, thanks I'll revisit after some time to see if proofs were created. Knowing the expected proof timeframes will help.

**Comment by jacohend** [comment]
@cogweh No problem. You can open a further issue here or contact me at jacob@tierion.com for questions.
